name: Use GitHub Action

on: push

jobs:

  generate_examples:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
          source-url: https://api.nuget.org/v3/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}

    - name: Build project
      run: dotnet build -c Release
    
    - name: Generate yumlmd
      id: generate_yumlmd
      uses: maisiesadler/deptree@v1.0.5
      env:
        ASSEMBLY_LOCATION: './src/DepTree/bin/Release/net5.0/DepTree.dll'
        ROOT_TYPES: 'DepTree.DependencyTree'
        INTERFACE_RESOLVER: None

    - name: Generate yuml
      id: generate_yuml
      uses: maisiesadler/deptree@v1.0.5
      env:
        ASSEMBLY_LOCATION: './src/DepTree/bin/Release/net5.0/DepTree.dll'
        ROOT_TYPES: 'DepTree.DependencyTree'
        INTERFACE_RESOLVER: None
        OUTPUT_FORMAT: yuml
    
    - name: Generate PlantUML
      id: generate_plantuml
      uses: maisiesadler/deptree@v1.0.5
      env:
        ASSEMBLY_LOCATION: './src/DepTree/bin/Release/net5.0/DepTree.dll'
        ROOT_TYPES: 'DepTree.DependencyTree'
        INTERFACE_RESOLVER: None
        OUTPUT_FORMAT: plantuml

    - name: Generate Mermaid
      id: generate_mermaidmd
      uses: maisiesadler/deptree@v1.0.5
      env:
        ASSEMBLY_LOCATION: './src/DepTree/bin/Release/net5.0/DepTree.dll'
        ROOT_TYPES: 'DepTree.DependencyTree'
        INTERFACE_RESOLVER: None
        OUTPUT_FORMAT: mermaidmd

    - name: Write outputs to file
      shell: bash
      run: |
        echo '${{ steps.generate_yumlmd.outputs.result }}' > example-outputs/yumlmd.md
        echo '${{ steps.generate_yuml.outputs.result }}' > example-outputs/yuml.yuml
        echo '${{ steps.generate_plantuml.outputs.result }}' > example-outputs/plantuml.puml
        echo '${{ steps.generate_mermaidmd.outputs.result }}' > example-outputs/mermaidmd.md

    - uses: EndBug/add-and-commit@v7
      name: Commit Changes
      with:
        default_author: github_actions
        message: 'Generate diagrams'
